# Generated by Django 2.2 on 2019-04-26 06:14

import datetime
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_mobile_mobile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(default=datetime.date(2019, 4, 26))),
                ('total_price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('price_payed', models.PositiveIntegerField()),
                ('installment_amount', models.PositiveIntegerField()),
                ('next_installment_due', models.DateField(default=datetime.date(2019, 5, 26))),
                ('amount_remaining', models.PositiveIntegerField()),
                ('installments_history', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None, verbose_name='History of installments payed')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(default=datetime.date(2019, 4, 26))),
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Mobile')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='supply.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='supply.Supplier'),
        ),
    ]
