# Generated by Django 2.2 on 2019-04-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase',
            new_name='order',
        ),
    ]
