# Generated by Django 2.2 on 2019-04-25 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='next_installment_due',
            field=models.DateField(default=datetime.date(2019, 5, 25)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateField(default=datetime.date(2019, 4, 25)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2019, 4, 25)),
        ),
    ]
