# Generated by Django 2.2 on 2019-04-29 10:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20190427_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.AlterField(
            model_name='order',
            name='next_installment_due',
            field=models.DateField(default=datetime.date(2019, 5, 29)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateField(default=datetime.date(2019, 4, 29)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2019, 4, 29)),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.PositiveIntegerField(choices=[(0, 'PERCENTAGE'), (1, 'ABSOLUTE')], default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='supply.Order')),
            ],
        ),
    ]
