# Generated by Django 2.2 on 2019-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_auto_20190429_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price after discount'),
        ),
    ]
