# Generated by Django 2.2 on 2019-04-29 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_order_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_discounts', to='supply.Order'),
        ),
    ]
