# Generated by Django 2.2 on 2019-04-30 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_auto_20190429_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='next_installment_due',
            field=models.DateField(default=datetime.date(2019, 5, 30)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateField(default=datetime.date(2019, 4, 30)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.date(2019, 4, 30)),
        ),
    ]
