# Generated by Django 2.2 on 2019-05-06 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_auto_20190506_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='next_installment_due',
            field=models.DateField(default=datetime.datetime(2019, 6, 5, 10, 11, 51, 289471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateField(default=datetime.datetime(2019, 5, 6, 10, 11, 51, 289320, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 6, 10, 11, 51, 288654, tzinfo=utc)),
        ),
    ]
