# Generated by Django 2.2 on 2019-05-27 09:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0009_auto_20190506_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='next_installment_due',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 9, 39, 10, 375245, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateField(default=datetime.datetime(2019, 5, 27, 9, 39, 10, 375185, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 27, 9, 39, 10, 374649, tzinfo=utc)),
        ),
    ]
