# Generated by Django 2.2 on 2019-07-09 07:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0010_auto_20190527_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='installment_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='next_installment_due',
            field=models.DateField(default=datetime.datetime(2019, 8, 8, 7, 42, 48, 982724, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_at',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 7, 42, 48, 982672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 7, 42, 48, 982232, tzinfo=utc)),
        ),
    ]
