# Generated by Django 2.2 on 2019-04-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('IPhone', 'IPhone'), ('QMobile', 'QMobile'), ('Huawei', 'Huawei'), ('Nokia', 'Nokia')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('mobile_status', models.CharField(choices=[('used', 'used'), ('New', 'New')], max_length=5)),
                ('IMEA_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('father_name', models.CharField(max_length=60)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('is_live_user', models.BooleanField(default=True, verbose_name='Is_Live_User')),
                ('is_maintenance_user', models.BooleanField(default=False, verbose_name='Maintenance_User')),
                ('address', models.CharField(max_length=250)),
                ('CNIC_number', models.IntegerField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(default=None)),
                ('amount_payed', models.PositiveIntegerField(default=0)),
                ('next_installment_due', models.DateField(default=None, verbose_name='Next Installment Date')),
                ('previous_installment_payed', models.DateField(default=None, verbose_name='Previous Installment Payed')),
                ('number_of_installments_payed', models.PositiveIntegerField(default=0, verbose_name='Number Of Installments Payed')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.Customer')),
                ('insurer_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_insurer', to='accounts.User')),
                ('insurer_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_insurer', to='accounts.User')),
                ('sold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='accounts.Mobile')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to='accounts.User'),
        ),
    ]
