# Generated by Django 2.2 on 2019-04-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_return', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('IPhone', 'IPhone'), ('QMobile', 'QMobile'), ('Huawei', 'Huawei'), ('Nokia', 'Nokia')], max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=10)),
                ('mobile_status', models.CharField(choices=[('used', 'used'), ('New', 'New')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_live_user', models.BooleanField(default=True, verbose_name='Is_Live_User')),
                ('is_maintenance_user', models.BooleanField(default=False, verbose_name='Maintenance_User')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField()),
                ('payed_amount', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounts.Customer')),
                ('sold_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='accounts.Mobile')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to='accounts.User'),
        ),
    ]
