# Generated by Django 2.2 on 2019-04-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CNIC_number',
            field=models.IntegerField(),
        ),
    ]
