# Generated by Django 2.2 on 2019-04-15 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(default=None)),
                ('amount_payed', models.PositiveIntegerField(default=0)),
                ('next_installment_due', models.DateField(default=None, verbose_name='Next Installment Date')),
                ('previous_installment_payed', models.DateField(default=None, verbose_name='Previous Installment Payed')),
                ('number_of_installments_payed', models.PositiveIntegerField(default=0, verbose_name='Number Of Installments Payed')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_to_return',
        ),
        migrations.AddField(
            model_name='mobile',
            name='IMEA_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.Customer'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='insurer_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_insurer', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='insurer_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_insurer', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sold_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='accounts.Mobile'),
        ),
    ]
