# Generated by Django 2.2 on 2019-04-16 07:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190416_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='installments_payed',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=None, size=None, verbose_name='History of installments payed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='CNIC_number',
            field=models.IntegerField(unique=True),
        ),
    ]
