# Generated by Django 2.2 on 2019-04-21 11:29

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190418_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_user',
            old_name='address',
            new_name='house_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='installments_payed',
        ),
        migrations.RemoveField(
            model_name='our_user',
            name='is_maintenance_user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='previous_installment_payed',
        ),
        migrations.AddField(
            model_name='our_user',
            name='business_address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='transactions',
            name='installments_payed',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None, verbose_name='History of installments payed'),
        ),
        migrations.AlterField(
            model_name='our_user',
            name='is_live_user',
            field=models.BooleanField(default=True, verbose_name='Is Live User'),
        ),
    ]
