# Generated by Django 2.2 on 2019-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190416_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
