# Generated by Django 2.2 on 2019-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190421_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='installment_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
