# Generated by Django 2.2 on 2019-04-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transactions_installment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.Customer'),
        ),
    ]
