# Generated by Django 2.2 on 2019-04-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transactions_is_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='installments_payed',
        ),
    ]
