# Generated by Django 2.2 on 2019-04-16 14:43

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customer_installments_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='installments_payed',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=[], size=None, verbose_name='History of installments payed'),
        ),
    ]
