# Generated by Django 2.2 on 2019-04-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190425_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='brand',
        ),
    ]
