# Generated by Django 2.2 on 2019-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_installments_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Is product in inventory or sold'),
        ),
    ]
