# Generated by Django 2.2 on 2019-04-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_mobile_mobile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_user',
            name='phone_number',
            field=models.CharField(default='', max_length=14),
        ),
    ]
