# Generated by Django 2.2 on 2019-04-17 05:53

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_mobile_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='installments_payed',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None, verbose_name='History of installments payed'),
        ),
    ]
