# Generated by Django 2.2 on 2019-04-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_our_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='IMEA_number',
            new_name='imei_number',
        ),
    ]
