# Generated by Django 2.2 on 2019-04-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190417_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
