# Generated by Django 2.2 on 2019-05-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190430_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='is_return',
            new_name='returned',
        ),
        migrations.CreateModel(
            name='TransactionReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_return', models.DateField(default=None)),
                ('amount_returned', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=450, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_transaction', to='accounts.Transactions')),
            ],
        ),
    ]
