# Generated by Django 2.2 on 2019-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190506_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
