# Generated by Django 2.2 on 2019-04-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190417_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='insurer_one',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='insurer_two',
        ),
    ]
